import pandas as pd
import numpy as np

import nltk
import re

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
data = {

    "Candidate_Name":[
        "Arun",
        "Karthik",
        "Priya",
        "Rahul",
        "Sanjay"
    ],


    "Resume_Text":[

        "Python developer machine learning artificial intelligence NLP SQL data science",

        "Java developer spring boot software testing database management",

        "Python NLP deep learning tensorflow machine learning data analytics",

        "Frontend developer HTML CSS JavaScript React UI UX",

        "Python Django Flask SQL machine learning cloud AWS"
    ]

}


df = pd.DataFrame(data)

df

  Candidate_Name                                        Resume_Text
0           Arun  Python developer machine learning artificial i...
1        Karthik  Java developer spring boot software testing da...
2          Priya  Python NLP deep learning tensorflow machine le...
3          Rahul  Frontend developer HTML CSS JavaScript React U...
4         Sanjay  Python Django Flask SQL machine learning cloud...

In [4]:
def clean_text(text):

    # lowercase
    text = text.lower()


    # remove special characters
    text = re.sub('[^a-zA-Z]', ' ', text)


    # tokenization
    words = word_tokenize(text)


    # remove stopwords
    stop_words = set(stopwords.words('english'))


    filtered_words=[]


    for word in words:

        if word not in stop_words:
            filtered_words.append(word)


    return " ".join(filtered_words)

In [5]:
df["Cleaned_Resume"] = df["Resume_Text"].apply(clean_text)

df

,Candidate_Name,Resume_Text,Cleaned_Resume
0,Arun,Python developer machine learning artificial i...,python developer machine learning artificial i...
1,Karthik,Java developer spring boot software testing da...,java developer spring boot software testing da...
2,Priya,Python NLP deep learning tensorflow machine le...,python nlp deep learning tensorflow machine le...
3,Rahul,Frontend developer HTML CSS JavaScript React U...,frontend developer html css javascript react u...
4,Sanjay,Python Django Flask SQL machine learning cloud...,python django flask sql machine learning cloud...

In [7]:
job_description = """

We are looking for Python Developer
with Machine Learning, NLP,
Artificial Intelligence, SQL,
Deep Learning and Cloud skills.

"""

In [8]:
clean_job = clean_text(job_description)


print(clean_job)

looking python developer machine learning nlp artificial intelligence sql deep learning cloud skills

In [9]:
documents = list(df["Cleaned_Resume"])


documents.append(clean_job)


documents

['python developer machine learning artificial intelligence nlp sql data science',
 'java developer spring boot software testing database management',
 'python nlp deep learning tensorflow machine learning data analytics',
 'frontend developer html css javascript react ui ux',
 'python django flask sql machine learning cloud aws',
 'looking python developer machine learning nlp artificial intelligence sql deep learning cloud skills']

In [10]:
tfidf = TfidfVectorizer()


tfidf_matrix = tfidf.fit_transform(documents)


print(tfidf_matrix.shape)

(6, 33)

In [11]:
resume_vectors = tfidf_matrix[:-1]


job_vector = tfidf_matrix[-1]


print(resume_vectors.shape)

print(job_vector.shape)

(5, 33)
(1, 33)

In [12]:
similarity = cosine_similarity(
    resume_vectors,
    job_vector
)


similarity

array([[0.61484704],
       [0.04557471],
       [0.47029675],
       [0.04557471],
       [0.39380482]])

In [26]:
df["Match_Percentage"] = (

    similarity * 100

).round(1)


df

,Candidate_Name,Resume_Text,Cleaned_Resume,Match_Percentage
0,Arun,Python developer machine learning artificial i...,python developer machine learning artificial i...,61.5
1,Karthik,Java developer spring boot software testing da...,java developer spring boot software testing da...,4.6
2,Priya,Python NLP deep learning tensorflow machine le...,python nlp deep learning tensorflow machine le...,47.0
3,Rahul,Frontend developer HTML CSS JavaScript React U...,frontend developer html css javascript react u...,4.6
4,Sanjay,Python Django Flask SQL machine learning cloud...,python django flask sql machine learning cloud...,39.4

In [27]:
ranking = df.sort_values(

    by="Match_Percentage",

    ascending=False

)


ranking

,Candidate_Name,Resume_Text,Cleaned_Resume,Match_Percentage
0,Arun,Python developer machine learning artificial i...,python developer machine learning artificial i...,61.5
2,Priya,Python NLP deep learning tensorflow machine le...,python nlp deep learning tensorflow machine le...,47.0
4,Sanjay,Python Django Flask SQL machine learning cloud...,python django flask sql machine learning cloud...,39.4
1,Karthik,Java developer spring boot software testing da...,java developer spring boot software testing da...,4.6
3,Rahul,Frontend developer HTML CSS JavaScript React U...,frontend developer html css javascript react u...,4.6

In [28]:
for index,row in ranking.iterrows():

    print("Candidate Name :",row["Candidate_Name"])

    print("Resume Match :",row["Match_Percentage"],"%")

    print("----------------------------")

Candidate Name : Arun
Resume Match : 61.5 %
----------------------------
Candidate Name : Priya
Resume Match : 47.0 %
----------------------------
Candidate Name : Sanjay
Resume Match : 39.4 %
----------------------------
Candidate Name : Karthik
Resume Match : 4.6 %
----------------------------
Candidate Name : Rahul
Resume Match : 4.6 %
----------------------------